enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  '@storybook/addon-docs@6.5.12':
    peerDependencies:
      '@babel/core': ^7.0.0-0
      webpack: '>=2'
  '@storybook/addon-postcss@2.0.0':
    peerDependencies:
      webpack: '^4.0.0 || ^5.0.0'
  '@storybook/docs-tools@6.5.12':
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: ^16.8.0 || ^17.0.0 || ^18.0.0
  '@storybook/mdx1-csf@0.0.1':
    peerDependencies:
      '@babel/core': ^7.0.0-0
  '@storybook/web-components@6.5.12':
    peerDependencies:
      '@babel/core': ^7.0.0-0
      webpack: '*'
  '@storybook/telemetry@6.5.12':
    peerDependencies:
      react: ^16.8.0 || ^17.0.0 || ^18.0.0
      react-dom: ^16.8.0 || ^17.0.0 || ^18.0.0
